server:
  port: 8080

spring:
  mail:
    host: smtp.gmail.com
    username: 
    password: 
    port: 587
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
        debug: false
